### ISSUE TITLE
Allow relative pathing for screenshots 

### ISSUE THREAD

**Issue by RezhaBlue** [nightwatchjs/html-reporter#22]
Hi All,
This is an enhancement request.
Our team uses nightwatch in a container then mirrors the output to local machines for review once test execution is over.
This correctly allows us to access the HTML file. However, the link in the file to screenshots is the full pathing in the container which differs from local causing image links in reporter to be broken.
Since file structure inside the test results output folder is consistent we were hoping to make use of relative pathing so the image links ergo overall report ends up more machine agnostic.

Thank you all for your work on this, it is immensely helpful!

**Comment by vaibhavsingh97** [comment]
Fixed in https://github.com/nightwatchjs/nightwatch/pull/3661
