### ISSUE TITLE
Add component tests

### ISSUE THREAD

**Issue by vaibhavsingh97** [nightwatchjs/html-reporter#39]
## Description
Currently, only `Header` and `Footer` have component tests. However, these tests are naive. We need to update them and create new tests for all other components.

## TODO
Add tests for these component: https://github.com/nightwatchjs/html-reporter/tree/main/src/components

## What do sample tests look like?

Let's see the Header component
![localhost_5173_](https://github.com/nightwatchjs/html-reporter/assets/8705386/474057dc-19f9-4fd3-89bc-7a8d987c3993)

Here, we can assert the presence and visibility of the Nightwatch.js logo. We can also verify that the "Test Report", date, and time are being rendered.

## Reference
https://nightwatchjs.org/guide/component-testing/write-jsx-react-tests.html

**Comment by adityak714** [comment]
Hello, I would like to take on this issue, if possible.

**Comment by vaibhavsingh97** [comment]
Sure, since multiple people can work on this master issue, it would be awesome if you could let us know which component you would like to add tests for by leaving a comment.

**Comment by adityak714** [comment]
I could start with the FilterDropdown and Search components.

**Comment by 0-sayed** [comment]
Hello, I would like to update Header and Footer, and create tests for tooltip

**Comment by Temidayo32** [comment]
@vaibhavsingh97  I will work on LogView

**Comment by aliamerj** [comment]
I will take AlertBanner

**Comment by aliamerj** [comment]
I will take ChipWithIcon

**Comment by piyushmishra1416** [comment]
I have opened a PR for AlertBanner component.

**Comment by JeremiahHerring** [comment]
I made a PR #56 for the FilePathView component

**Comment by Ankuristic** [comment]
is AlertBanner Component is still tested

**Comment by Ankuristic** [comment]
Hi @vaibhavsingh97 i am doing the FilterDropdown component test

**Comment by JeremiahHerring** [comment]
Created Draft PR #58 for ErrorFallBack Component, still need to add more test functionalities but it's a good start to the test file

**Comment by bboinnovate20** [comment]
Added test Timer Component  https://github.com/nightwatchjs/html-reporter/pull/63

**Comment by bboinnovate20** [comment]
#63

**Comment by bboinnovate20** [comment]
> Added test Timer Component #63

https://github.com/nightwatchjs/html-reporter/pull/63#issue-2211237172

**Comment by bboinnovate20** [comment]
https://github.com/nightwatchjs/html-reporter/pull/63#issue-2211237172

**Comment by SohaibMagrabi** [comment]
added test search component

**Comment by SohaibMagrabi** [comment]
added test  for separator and screenshot components
